{% set name = "pogo" %}
{% set version = "9.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/pogo/-/archive/{{ version }}/pogo-{{ version }}.tar.gz
  sha256: 7cff020f2f250da4bb02e7da56d8f98f9bdc38618ca13ad9f455b049402c47f0

build:
  number: 1

requirements:
  build:
    - openjdk 11
    - maven
    - sed  # [osx]
  run:
    - openjdk >=11,<16a0

test:
  commands:
    - test -f ${PREFIX}/share/java/Pogo.jar                                     # [unix]
    - test -f ${PREFIX}/share/java/Pogo-${PKG_VERSION}.jar                      # [unix]
    - test -f ${PREFIX}/share/pogo/preferences/Pogo.site_properties             # [unix]
    - test -f ${PREFIX}/bin/pogo                                                # [unix]
    - if not exist %PREFIX%\share\java\Pogo.jar exit 1                          # [win]
    - if not exist %PREFIX%\share\pogo\preferences\Pogo.site_properties exit 1  # [win]
    - if not exist %PREFIX%\Scripts\pogo.bat exit 1                             # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - aggregate-third-party-report.html
  summary: GUI application for generating Tango projects
  description: |
    Pogo is the TANGO code generator.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/pogo
  doc_url: https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/built-in/pogo/index.html

extra:
  recipe-maintainers:
    - beenje
    - dlacoste-esrf
